kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: storageoscluster-operator
  labels:
    app: storageoscluster-operator
subjects:
- kind: ServiceAccount
  name: storageoscluster-operator-sa
  namespace: storageos-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
