apiVersion: "storageos.com/v1"
kind: StorageOSCluster
metadata:
  name: "storageos"
spec:
  secretRefName: "storageos-api" # Reference from the Secret created in the previous step
  secretRefNamespace: "default"  # Namespace of the Secret
  images:
    nodeContainer: "storageos/node:1.5.2"
  sharedDir: '/var/lib/kubelet/plugins/kubernetes.io~storageos' # Needed when Kubelet as a container
  k8sDistro: "dockeree"
  csi:
    enable: true
    deploymentStrategy: "deployment"
  resources:
    requests:
      memory: "512Mi"
  #nodeSelectorTerms:
    #- matchExpressions:
      #- key: "node-role.kubernetes.io/compute" # According to the labels you defined in your nodes
        #operator: In
        #values:
        #- ""

