apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-32279-0
  labels:
    storageos.com/hint.master: "$NODE"
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-32279-1
  labels:
    storageos.com/hint.master: "$NODE"
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-32279-2
  labels:
    storageos.com/hint.master: "$NODE"
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-32279-3
  labels:
    storageos.com/hint.master: "$NODE"
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio-4vol
spec:
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: "$NODE"
      containers:
      - name: fio
        image: senax/docker-fio:latest
        command:
          - "fio"
          - "/tmp/profile-4vol.fio"
        volumeMounts:
          - name: fio-conf
            mountPath: /tmp/
          - name: vol0
            mountPath: /mnt/pvc0
          - name: vol1
            mountPath: /mnt/pvc1
          - name: vol2
            mountPath: /mnt/pvc2
          - name: vol3
            mountPath: /mnt/pvc3
        resources:
          requests:
            cpu: 500m
      volumes:
      - name: fio-conf
        configMap:
          name: fio-profiles-local
      - name: vol0
        persistentVolumeClaim:
          claimName: pvc-32279-0
      - name: vol1
        persistentVolumeClaim:
          claimName: pvc-32279-1
      - name: vol2
        persistentVolumeClaim:
          claimName: pvc-32279-2
      - name: vol3
        persistentVolumeClaim:
          claimName: pvc-32279-3
