---
apiVersion: v1
kind: Service
metadata:
  name: es-data
  # namespace: elasticsearch
  labels:
    component: elasticsearch
    role: esdata
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    component: elasticsearch
    role: esdata
