---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
  # namespace: elasticsearch
  labels:
    component: elasticsearch
    role: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: exporter
  template:
    metadata:
      labels:
        component: elasticsearch
        role: exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9108"
    spec:
      serviceAccountName: elasticsearch
      containers:
      - name: es-exporter
        imagePullPolicy: IfNotPresent
        image: justwatch/elasticsearch_exporter:1.0.2
        command:
          - "/bin/elasticsearch_exporter"
        args:
          - "-es.uri=http://elasticsearch:9200"
          - "-es.all"
          - "-es.indices"
          - "-es.timeout=5s"
        ports:
          - containerPort: 9108
            name: scrape
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            memory: 65Mi
            cpu: 100m
        livenessProbe:
          tcpSocket:
            port: scrape
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: scrape
          initialDelaySeconds: 15
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: es-exporter
  labels:
    component: elasticsearch
    role: exporter
spec:
  ports:
  - port: 9108
    name: scrape
  clusterIP: None
  selector:
    component: elasticsearch
    role: exporter
